# Dependabot configuration
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Keep npm dependencies up to date
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  # Keep dev container base image up to date
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
